using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Application.Contracts;
using Models;

namespace Application.Services.CategoryServices
{
    public class CategoryService : ICategoryService
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryService(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IEnumerable<Category>> GetAllAsync() => await _unitOfWork.Categories.GetAllAsync();

        public async Task<Category?> GetByIdAsync(Guid id) => await _unitOfWork.Categories.GetByIdAsync(id);

        public async Task AddAsync(CategoryDto dto)
        {
            var category = new Category
            {
                CategoryID = 0, // Assuming CategoryID is auto-generated by the database, set it to a default value like 0.
                Name = dto.Name
            };
            await _unitOfWork.Categories.AddAsync(category);
            await _unitOfWork.SaveAsync();
        }

        public async Task UpdateAsync(Guid id, CategoryDto dto)
        {
            var category = await _unitOfWork.Categories.GetByIdAsync(id);
            if (category == null) return;

            category.Name = dto.Name;
            _unitOfWork.Categories.Update(category);
            await _unitOfWork.SaveAsync();
        }

        public async Task DeleteAsync(Guid id)
        {
            var category = await _unitOfWork.Categories.GetByIdAsync(id);
            if (category == null) return;

            _unitOfWork.Categories.Delete(category);
            await _unitOfWork.SaveAsync();
        }
    }
}
